steps:
- task: NodeTool@0
  inputs:
    versionSpec: "$(NODE_VERSION)"

- powershell: |
    curl -fsSL https://bun.sh/install | bash -s "bun-v$(BUN_VERSION)"
    Write-Host "##vso[task.prependpath]$HOME/.bun/bin"
    $env:PATH="$HOME/.bun/bin:$env:PATH"
    bun --version
  displayName: Setup Bun

- powershell: |
    sudo apt-get update && sudo apt-get install -y gcc libseccomp-dev
  displayName: Install seccomp build dependencies

- powershell: |
    npm run build:seccomp
  displayName: Build seccomp

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: "vendor/seccomp/$(NPM_ARCH)"
    artifact: "seccomp-$(NPM_ARCH)"
    publishLocation: "pipeline"
